apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: asia-southeast1-docker.pkg.dev/speedy-victory-336109/singapore-repo/fschat:v1
        name: api
        command:
          - python3
          - -m
          - fastchat.serve.openai_api_server
          - --controller
          - http://controller-svc:21001
          - --host
          - "0.0.0.0"
          - --port
          - "8000"
        ports:
        - containerPort: 8000
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool        

---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: api
  type: LoadBalancer